version: "3.8"

services:
  backend:
    image: backend
    build: ./server/flask
    restart: always
    environment:
      FLASK_RUN_PORT: "5000"
      FLASK_RUN_HOST: "0.0.0.0"
    ports:
      - "8000:5000"
  
  frontend:
    image: frontend
    build: ./client
    depends_on:
      - backend
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"

